// Deterministic, no-LLM digest builder for the Sutro Almanac.
//
// Reads the Telegram archive (telegram.db) and the SutroYaro docs tree, then
// emits one provenance digest per calendar month to digests/. The digest is the
// raw material each recap is written FROM: every claim in a recap should trace
// back to a line here (a Telegram message, a shared URL, a changelog release, or
// a catch-up). Nothing in this script summarizes or paraphrases - it only counts,
// extracts, and flags - so the source material cannot be invented.
//
// Run: bun scripts/build-digest.ts
// Output is gitignored: digests/ contains private message text and is never published.

import { Database } from "bun:sqlite";
import {
  readdirSync,
  readFileSync,
  writeFileSync,
  mkdirSync,
  existsSync,
} from "node:fs";
import { join } from "node:path";

const SUTROYARO =
  process.env.SUTROYARO ?? "../SutroYaro";
const DB_PATH = process.env.TELEGRAM_DB ?? join(SUTROYARO, "telegram.db");
const DOCS_DIR = join(SUTROYARO, "docs");
const OUT_DIR = join(import.meta.dir, "..", "digests");

const ym = (d) => d.slice(0, 7);
const day = (d) => d.slice(0, 10);
const oneLine = (s, n = 220) => {
  const t = s.replace(/\s+/g, " ").trim();
  return t.length > n ? t.slice(0, n - 1) + "..." : t;
};

// --- URL extraction + categorization ----------------------------------------
const URL_RE = /https?:\/\/[^\s<>()\[\]"'`]+/g;
const stripTrail = (u) => u.replace(/[.,;:!?)\]]+$/, "");
function category(url) {
  const u = url.toLowerCase();
  if (u.includes("arxiv.org")) return "arxiv";
  if (u.includes("github.com")) return "github";
  if (u.includes("colab.research.google") || u.includes("colab.google"))
    return "colab";
  if (u.includes("docs.google.com") || u.includes("drive.google.com"))
    return "gdocs";
  if (u.includes("youtube.com") || u.includes("youtu.be")) return "youtube";
  if (u.includes("x.com/") || u.includes("twitter.com")) return "twitter";
  return "other";
}
const CAT_ORDER = ["arxiv", "github", "colab", "gdocs", "youtube", "twitter", "other"];

// --- candidate-signal heuristics (recall over precision; I read + judge) ------
const SIGNALS = [
  [
    "decisions",
    /\b(decid(?:e|ed|es|ing)|decision|agreed|consensus|we'?ll go with|let'?s go with|going with|conclusion|resolved that)\b/i,
  ],
  [
    "results",
    /\b(result|finding|headline|solved|beats?|outperforms?|speedup|\d+x\s*(?:faster|fewer|better|cheaper|lower|worse)|wins?\b|works now|fails? (?:completely|at)|breakthrough)\b/i,
  ],
  [
    "questions",
    /(?:\?\s*$|\bopen question\b|\bnext step|\btodo\b|\bfollow.?up\b|\bshould we\b|\bquestion:)/i,
  ],
];

// --- load telegram -----------------------------------------------------------
const db = new Database(DB_PATH, { readonly: true });
const rows = db
  .query(
    `SELECT m.id, m.topic_id, t.title AS topic, m.date, m.sender, m.text
     FROM messages m JOIN topics t ON t.id = m.topic_id
     ORDER BY m.date ASC`
  )
  .all();
db.close();

const byMonth = new Map();
for (const r of rows) {
  const k = ym(r.date);
  if (!byMonth.has(k)) byMonth.set(k, []);
  byMonth.get(k).push(r);
}

// --- parse changelog into dated releases bucketed by month -------------------
function parseChangelog() {
  const p = join(DOCS_DIR, "changelog.md");
  const byM = new Map();
  if (!existsSync(p)) return byM;
  let cur = null;
  for (const line of readFileSync(p, "utf8").split("\n")) {
    const h = line.match(/^##\s+\[([^\]]+)\]\s*-\s*(\d{4}-\d{2}-\d{2})/);
    if (h) {
      cur = { version: h[1], date: h[2], sections: [] };
      const k = ym(h[2]);
      if (!byM.has(k)) byM.set(k, []);
      byM.get(k).push(cur);
      continue;
    }
    const s = line.match(/^###\s+(.+)/);
    if (s && cur) cur.sections.push(s[1].trim());
  }
  return byM;
}
const changelogByMonth = parseChangelog();

// --- catch-ups bucketed by month (filename is the date) ----------------------
function catchupsByMonth() {
  const dir = join(DOCS_DIR, "catchups");
  const byM = new Map();
  if (!existsSync(dir)) return byM;
  for (const f of readdirSync(dir)) {
    const m = f.match(/^(\d{4}-\d{2}-\d{2})\.md$/);
    if (!m) continue;
    const k = ym(m[1]);
    if (!byM.has(k)) byM.set(k, []);
    byM.get(k).push(f);
  }
  return byM;
}
const catchups = catchupsByMonth();

// --- build per-month digests -------------------------------------------------
mkdirSync(OUT_DIR, { recursive: true });
const months = [...byMonth.keys()].sort();
const indexLines = [
  "# Digest index",
  "",
  "Deterministic provenance extracts (Telegram + docs). Generated by `scripts/build-digest.ts`.",
  "**Gitignored - contains private message text.**",
  "",
  "| Month | Telegram msgs | Unique links | Changelog releases | Catch-ups |",
  "|---|--:|--:|--:|--:|",
];

for (const month of months) {
  const msgs = byMonth.get(month);

  // topic volume
  const topicMap = new Map();
  for (const m of msgs) {
    if (!topicMap.has(m.topic))
      topicMap.set(m.topic, { n: 0, senders: new Set(), first: m.date, last: m.date });
    const t = topicMap.get(m.topic);
    t.n++;
    t.senders.add(m.sender);
    if (m.date < t.first) t.first = m.date;
    if (m.date > t.last) t.last = m.date;
  }

  // links (dedup by URL, keep first sighting + a count)
  const links = new Map();
  for (const m of msgs) {
    const found = m.text.match(URL_RE);
    if (!found) continue;
    for (let u of found) {
      u = stripTrail(u);
      if (links.has(u)) {
        links.get(u).count++;
        continue;
      }
      links.set(u, {
        url: u,
        cat: category(u),
        date: day(m.date),
        sender: m.sender,
        topic: m.topic,
        snippet: oneLine(m.text),
        count: 1,
      });
    }
  }

  // candidate signal lines
  const sig = { decisions: [], results: [], questions: [] };
  for (const m of msgs) {
    if (!m.text) continue;
    for (const [name, re] of SIGNALS) if (re.test(m.text)) sig[name].push(m);
  }

  // longest messages (often the substantive ones), excluding bare links
  const substantive = [...msgs]
    .filter((m) => m.text && !/^https?:\/\/\S+$/.test(m.text.trim()))
    .sort((a, b) => b.text.length - a.text.length)
    .slice(0, 15);

  // render
  const out = [];
  out.push(`# Digest - ${month}`);
  out.push("");
  out.push("> Deterministic extract for writing this month's recap - Telegram + docs provenance.");
  out.push("> Generated by `scripts/build-digest.ts`. **Contains private message text; do not publish raw.**");
  out.push("");

  out.push(`## Telegram volume - ${msgs.length} messages`);
  out.push("");
  out.push("| Topic | Msgs | People | First | Last |");
  out.push("|---|--:|--:|---|---|");
  for (const [topic, t] of [...topicMap.entries()].sort((a, b) => b[1].n - a[1].n))
    out.push(`| ${topic} | ${t.n} | ${t.senders.size} | ${day(t.first)} | ${day(t.last)} |`);
  out.push("");

  const linksByCat = new Map();
  for (const l of links.values()) {
    if (!linksByCat.has(l.cat)) linksByCat.set(l.cat, []);
    linksByCat.get(l.cat).push(l);
  }
  out.push(`## Links shared - ${links.size} unique`);
  out.push("");
  for (const cat of CAT_ORDER) {
    const arr = linksByCat.get(cat);
    if (!arr || !arr.length) continue;
    out.push(`### ${cat} (${arr.length})`);
    for (const l of arr.sort((a, b) => a.date.localeCompare(b.date))) {
      out.push(
        `- ${l.date} · ${l.sender} · _${l.topic}_ - <${l.url}>${l.count > 1 ? ` ×${l.count}` : ""}`
      );
      out.push(`  > ${l.snippet}`);
    }
    out.push("");
  }

  out.push("## Candidate signal lines");
  out.push("");
  for (const [name] of SIGNALS) {
    const arr = sig[name];
    const shown = arr.slice(0, 50);
    out.push(
      `### ${name} - ${arr.length} matched${arr.length > shown.length ? `, ${shown.length} shown` : ""}`
    );
    for (const m of shown)
      out.push(`- ${day(m.date)} · ${m.sender} · _${m.topic}_ - ${oneLine(m.text, 200)}`);
    out.push("");
  }

  out.push(`## Longest messages (top ${substantive.length})`);
  for (const m of substantive)
    out.push(`- ${day(m.date)} · ${m.sender} · _${m.topic}_ - ${oneLine(m.text, 260)}`);
  out.push("");

  out.push(`## Docs covering ${month}`);
  out.push("");
  const cl = changelogByMonth.get(month) || [];
  if (cl.length) {
    out.push(`### Changelog releases (${cl.length})`);
    for (const v of cl)
      out.push(`- **v${v.version}** (${v.date})${v.sections.length ? ` - ${v.sections.join("; ")}` : ""}`);
    out.push("");
  }
  const cu = catchups.get(month) || [];
  if (cu.length) {
    out.push("### Catch-ups");
    for (const f of cu) out.push(`- \`docs/catchups/${f}\``);
    out.push("");
  }

  writeFileSync(join(OUT_DIR, `${month}.md`), out.join("\n"));
  indexLines.push(`| ${month} | ${msgs.length} | ${links.size} | ${cl.length} | ${cu.length} |`);
}

writeFileSync(join(OUT_DIR, "index.md"), indexLines.join("\n") + "\n");
console.log(`Wrote ${months.length} month digests + index to ${OUT_DIR}`);
for (const m of months) console.log(`  ${m}: ${byMonth.get(m).length} msgs`);
